import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Image from 'next/image'
import HomePageHeader from '../components/HomePageHeader'
import OurWork from '../components/OurWork'
import LatestWork from '../components/LatestWork'
import { Fragment } from 'react'
import { Disclosure, Menu, Transition } from '@headlessui/react'
import { Bars3Icon, BellIcon, XMarkIcon, ShareIcon } from '@heroicons/react/24/outline'
import ProductLife from '../components/ProductLife';



export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Devsoful</title>
        <meta name="description" content="Generated by create next app" />

        <link rel="icon" href="/favicon.ico" />

      </Head>
      <main >
        {/* Navar Start */}
        <HomePageHeader />
        {/* NavBar End */}
        <OurWork />
        <ProductLife />
        <LatestWork />

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
